### ISSUE TITLE
Merge cjheath/hackrf?

### ISSUE THREAD

**Issue by uranuspucksaxophone** [uranuspucksaxophone/hackrf-improved#11]

**Comment by cjheath** [comment]
Feel free to contact me for discussion. Over a thousand of my units have been sold, and zero reported failures so far.

But you're going to need to think long and hard about what you really want to achieve. The cost of parts for HackRF One is around $US50. You want to start with a receive chip that costs $US220, you're building a different beast and need to look at the capabilities and positioning of the competing products. Simply building a wider faster data path will not produce a competitive product, because the HackRF has many other problem: spurs, images, poor sensitivity, intermodulation, etc. It lacks appropriate filters to avoid these problems.

I also want to design an SDR with a fast wide channel, and a big enough FPGA to run flexible filters and demodulators, to reduce the signal bandwidth to the host (rather than relying on faster USB connectivity). But it needs to be a green-fields approach with a proper analysis of the analog parts of the signal processing and conversion chain.

**Comment by uranuspucksaxophone** [comment]
Well, thank you, in that case, we would have to fix all the HackRF issues and then, maybe beefing it up a bit. The rough schematics are coming today, so stay tuned.
